<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>DesktopPeople.Windows</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);SYSLIB1054</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DesktopPeople.Core\DesktopPeople.Core.csproj" />
  </ItemGroup>
</Project>
